### PR TITLE
Feature - #64 additional aliases performance optimization

### PR DESCRIPTION
**Pull request by Ocramius**
Provides new benchmarking framework (and instructions), provides constant time benchmarking, improves performance of aliasing resolution

See zendframework/zend-servicemanager#64

### CODE REVIEW

**Comment by Ocramius** [comment]
Linking phpbench/phpbench/issues/304 (relevant)

**Comment by bakura10** [comment]
Can you post some results of the I lining stuff? I'm curious to learn about the cost of a function call in php7.

**Comment by Ocramius** [comment]
@bakura10 

### output with ocramius/zend-servicemanager@44d7b0d

(before inlining)

```
+-----------------------------+----------------------------------+-------+--------+------+-----+-------------+-------------+-------------+-------------+-------------+----------+--------+--------------+
| benchmark                   | subject                          | group | params | revs | its | mem         | best        | mean        | mode        | worst       | stdev    | rstdev | diff         |
+-----------------------------+----------------------------------+-------+--------+------+-----+-------------+-------------+-------------+-------------+-------------+----------+--------+--------------+
| FetchCachedServicesBench    | benchFetchFactory1               |       | []     | 1000 | 20  | 957,232b    | 1.858μs     | 1.950μs     | 1.917μs     | 2.043μs     | 0.053μs  | 2.73%  | +2.62%       |
| FetchCachedServicesBench    | benchFetchInvokable1             |       | []     | 1000 | 20  | 957,232b    | 1.852μs     | 1.901μs     | 1.877μs     | 1.990μs     | 0.039μs  | 2.06%  | +0.06%       |
| FetchCachedServicesBench    | benchFetchService1               |       | []     | 1000 | 20  | 957,232b    | 1.855μs     | 1.922μs     | 1.920μs     | 2.013μs     | 0.041μs  | 2.12%  | +1.19%       |
| FetchCachedServicesBench    | benchFetchAlias1                 |       | []     | 1000 | 20  | 957,232b    | 1.845μs     | 1.900μs     | 1.893μs     | 1.969μs     | 0.034μs  | 1.79%  | 0.00%        |
| FetchCachedServicesBench    | benchFetchRecursiveAlias1        |       | []     | 1000 | 20  | 957,240b    | 1.870μs     | 1.949μs     | 1.948μs     | 2.020μs     | 0.041μs  | 2.11%  | +2.59%       |
| FetchCachedServicesBench    | benchFetchRecursiveAlias2        |       | []     | 1000 | 20  | 957,240b    | 1.861μs     | 1.938μs     | 1.921μs     | 2.031μs     | 0.044μs  | 2.29%  | +1.99%       |
| FetchCachedServicesBench    | benchFetchAbstractFactoryService |       | []     | 1000 | 20  | 957,248b    | 8.386μs     | 8.688μs     | 8.603μs     | 9.092μs     | 0.195μs  | 2.24%  | +357.30%     |
| FetchNewServiceManagerBench | benchFetchServiceManagerCreation |       | []     | 100  | 20  | 24,056,768b | 2,516.450μs | 2,588.650μs | 2,559.799μs | 2,709.070μs | 52.613μs | 2.03%  | +136,159.08% |
| FetchNewServicesBench       | benchFetchFactory1               |       | []     | 1000 | 10  | 960,432b    | 8.402μs     | 8.697μs     | 8.661μs     | 8.936μs     | 0.160μs  | 1.84%  | +357.78%     |
| FetchNewServicesBench       | benchBuildFactory1               |       | []     | 1000 | 10  | 960,432b    | 8.029μs     | 8.177μs     | 8.150μs     | 8.478μs     | 0.119μs  | 1.46%  | +330.40%     |
| FetchNewServicesBench       | benchFetchInvokable1             |       | []     | 1000 | 10  | 960,432b    | 9.826μs     | 10.298μs    | 10.150μs    | 10.679μs    | 0.275μs  | 2.67%  | +442.06%     |
| FetchNewServicesBench       | benchBuildInvokable1             |       | []     | 1000 | 10  | 960,432b    | 8.276μs     | 8.581μs     | 8.625μs     | 8.909μs     | 0.202μs  | 2.36%  | +351.68%     |
| FetchNewServicesBench       | benchFetchService1               |       | []     | 1000 | 10  | 960,432b    | 1.888μs     | 1.964μs     | 1.991μs     | 2.026μs     | 0.046μs  | 2.36%  | +3.40%       |
| FetchNewServicesBench       | benchFetchFactoryAlias1          |       | []     | 1000 | 10  | 960,432b    | 8.130μs     | 8.461μs     | 8.409μs     | 8.883μs     | 0.199μs  | 2.36%  | +345.36%     |
| FetchNewServicesBench       | benchBuildFactoryAlias1          |       | []     | 1000 | 10  | 960,432b    | 8.427μs     | 8.609μs     | 8.618μs     | 8.769μs     | 0.113μs  | 1.31%  | +353.13%     |
| FetchNewServicesBench       | benchFetchRecursiveFactoryAlias1 |       | []     | 1000 | 10  | 960,448b    | 8.040μs     | 8.381μs     | 8.369μs     | 8.662μs     | 0.158μs  | 1.89%  | +341.13%     |
| FetchNewServicesBench       | benchBuildRecursiveFactoryAlias1 |       | []     | 1000 | 10  | 960,448b    | 8.301μs     | 8.648μs     | 8.779μs     | 8.942μs     | 0.211μs  | 2.44%  | +355.18%     |
| FetchNewServicesBench       | benchFetchRecursiveFactoryAlias2 |       | []     | 1000 | 10  | 960,448b    | 7.985μs     | 8.224μs     | 8.180μs     | 8.454μs     | 0.139μs  | 1.69%  | +332.88%     |
| FetchNewServicesBench       | benchBuildRecursiveFactoryAlias2 |       | []     | 1000 | 10  | 960,448b    | 8.071μs     | 8.410μs     | 8.433μs     | 8.775μs     | 0.212μs  | 2.52%  | +342.68%     |
| FetchNewServicesBench       | benchFetchAbstractFactoryFoo     |       | []     | 1000 | 10  | 960,440b    | 8.492μs     | 8.818μs     | 8.738μs     | 9.197μs     | 0.215μs  | 2.44%  | +364.13%     |
| FetchNewServicesBench       | benchBuildAbstractFactoryFoo     |       | []     | 1000 | 10  | 960,440b    | 7.944μs     | 8.229μs     | 8.237μs     | 8.579μs     | 0.194μs  | 2.36%  | +333.17%     |
+-----------------------------+----------------------------------+-------+--------+------+-----+-------------+-------------+-------------+-------------+-------------+----------+--------+--------------+
```

### output with ocramius/zend-servicemanager@4989b18

```
+-----------------------------+----------------------------------+-------+--------+------+-----+-------------+-----------+-----------+-----------+-----------+----------+--------+-------------+
| benchmark                   | subject                          | group | params | revs | its | mem         | best      | mean      | mode      | worst     | stdev    | rstdev | diff        |
+-----------------------------+----------------------------------+-------+--------+------+-----+-------------+-----------+-----------+-----------+-----------+----------+--------+-------------+
| FetchCachedServicesBench    | benchFetchFactory1               |       | []     | 1000 | 20  | 956,096b    | 1.887μs   | 1.954μs   | 1.923μs   | 2.049μs   | 0.049μs  | 2.52%  | +2.49%      |
| FetchCachedServicesBench    | benchFetchInvokable1             |       | []     | 1000 | 20  | 956,096b    | 1.855μs   | 1.926μs   | 1.894μs   | 2.021μs   | 0.051μs  | 2.65%  | +1.02%      |
| FetchCachedServicesBench    | benchFetchService1               |       | []     | 1000 | 20  | 956,096b    | 1.942μs   | 1.995μs   | 1.968μs   | 2.072μs   | 0.041μs  | 2.07%  | +4.60%      |
| FetchCachedServicesBench    | benchFetchAlias1                 |       | []     | 1000 | 20  | 956,096b    | 1.895μs   | 1.960μs   | 1.978μs   | 2.024μs   | 0.036μs  | 1.85%  | +2.78%      |
| FetchCachedServicesBench    | benchFetchRecursiveAlias1        |       | []     | 1000 | 20  | 956,104b    | 1.864μs   | 1.952μs   | 1.992μs   | 2.028μs   | 0.050μs  | 2.55%  | +2.35%      |
| FetchCachedServicesBench    | benchFetchRecursiveAlias2        |       | []     | 1000 | 20  | 956,104b    | 1.860μs   | 1.907μs   | 1.881μs   | 2.001μs   | 0.040μs  | 2.10%  | 0.00%       |
| FetchCachedServicesBench    | benchFetchAbstractFactoryService |       | []     | 1000 | 20  | 956,112b    | 8.368μs   | 8.604μs   | 8.590μs   | 8.932μs   | 0.141μs  | 1.64%  | +351.21%    |
| FetchNewServiceManagerBench | benchFetchServiceManagerCreation |       | []     | 100  | 20  | 24,055,808b | 896.980μs | 933.835μs | 918.284μs | 975.300μs | 21.613μs | 2.31%  | +48,873.91% |
| FetchNewServicesBench       | benchFetchFactory1               |       | []     | 1000 | 10  | 959,296b    | 8.598μs   | 8.941μs   | 8.966μs   | 9.260μs   | 0.184μs  | 2.06%  | +368.90%    |
| FetchNewServicesBench       | benchBuildFactory1               |       | []     | 1000 | 10  | 959,296b    | 7.998μs   | 8.165μs   | 8.165μs   | 8.324μs   | 0.100μs  | 1.23%  | +328.22%    |
| FetchNewServicesBench       | benchFetchInvokable1             |       | []     | 1000 | 10  | 959,296b    | 9.084μs   | 9.356μs   | 9.342μs   | 9.589μs   | 0.151μs  | 1.62%  | +390.64%    |
| FetchNewServicesBench       | benchBuildInvokable1             |       | []     | 1000 | 10  | 959,296b    | 7.997μs   | 8.313μs   | 8.221μs   | 8.639μs   | 0.198μs  | 2.38%  | +335.96%    |
| FetchNewServicesBench       | benchFetchService1               |       | []     | 1000 | 10  | 959,296b    | 1.891μs   | 1.975μs   | 1.960μs   | 2.068μs   | 0.049μs  | 2.46%  | +3.57%      |
| FetchNewServicesBench       | benchFetchFactoryAlias1          |       | []     | 1000 | 10  | 959,296b    | 8.114μs   | 8.286μs   | 8.269μs   | 8.589μs   | 0.130μs  | 1.57%  | +334.56%    |
| FetchNewServicesBench       | benchBuildFactoryAlias1          |       | []     | 1000 | 10  | 959,296b    | 7.967μs   | 8.092μs   | 8.045μs   | 8.433μs   | 0.130μs  | 1.60%  | +324.38%    |
| FetchNewServicesBench       | benchFetchRecursiveFactoryAlias1 |       | []     | 1000 | 10  | 959,312b    | 7.945μs   | 8.149μs   | 8.058μs   | 8.492μs   | 0.171μs  | 2.10%  | +327.35%    |
| FetchNewServicesBench       | benchBuildRecursiveFactoryAlias1 |       | []     | 1000 | 10  | 959,312b    | 7.941μs   | 8.112μs   | 8.042μs   | 8.417μs   | 0.148μs  | 1.83%  | +325.42%    |
| FetchNewServicesBench       | benchFetchRecursiveFactoryAlias2 |       | []     | 1000 | 10  | 959,312b    | 7.950μs   | 8.131μs   | 8.071μs   | 8.381μs   | 0.126μs  | 1.55%  | +326.41%    |
| FetchNewServicesBench       | benchBuildRecursiveFactoryAlias2 |       | []     | 1000 | 10  | 959,312b    | 7.960μs   | 8.144μs   | 8.110μs   | 8.429μs   | 0.121μs  | 1.48%  | +327.10%    |
| FetchNewServicesBench       | benchFetchAbstractFactoryFoo     |       | []     | 1000 | 10  | 959,304b    | 8.390μs   | 8.537μs   | 8.587μs   | 8.618μs   | 0.081μs  | 0.95%  | +347.73%    |
| FetchNewServicesBench       | benchBuildAbstractFactoryFoo     |       | []     | 1000 | 10  | 959,304b    | 7.867μs   | 7.935μs   | 7.919μs   | 8.052μs   | 0.054μs  | 0.68%  | +316.12%    |
+-----------------------------+----------------------------------+-------+--------+------+-----+-------------+-----------+-----------+-----------+-----------+----------+--------+-------------+
```

So it's `2,588.650μs` (before), `933.835μs` (after).

**Comment by bakura10** [comment]
Pretty nice. Everything's matter ;).

**Pull request merged**
